### ISSUE TITLE
fixes sorted files moving

### ISSUE THREAD

**Issue by z9877969** [YuriiRogovets/node-team-01#1]
```
async function moveFile(filePath, dirName, fileName) {
  const finallyPath = path.join(targetPath, dirName);
  if (!dirStorage[dirName]) {
    dirStorage[dirName] = true;
    await fs.mkdir(finallyPath);
  }
  await fs.rename(filePath, path.join(finallyPath, fileName));
}
```
в `dirStorage` потрібно зробити запис про створену папку перед створенням папки, тобто викликом `fs.mkdir`, щоб коректно взаємодіяти з `diskStorage` в асинхронних функціях

**Comment by YuriiRogovets** [comment]
всього два рядки місцями поміняти? )

вс, 5 мая 2024 г. в 13:53, Andriy Kyrylenko ***@***.***>:
